name: Test Against Regression
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: ensure correct user
        run: chown -R root /__w/cdktf-integration-serverless-python-example/
      - name: Generate Pipfile.lock
        run: pipenv lock
      - name: Install Python Dependencies
        run: pipenv requirements | sed -nE 's/^([[:alnum:]-]+==[0-9]+\.[0-9]+\.[0-9]+).*$/\1/p' | PIPENV_VENV_IN_PROJECT=1 bash -c 'dependencies=$(cat); echo "$dependencies" | while read -r requirement; do echo "INSTALLING $requirement"; pipenv run pip install "$requirement"; done'
      - name: Pytest
        run: pipenv run pytest test_against_regression.py
